買い物プロセス ゲスト購入でお客様情報入力へ戻ると生年月日が補完されない #1008
EC-CUBE/ec-cube2 pull request #1011
Opened 2024-09-28 01:56 UTC by clicktx

fixed #1008

2024-09-29 13:44 UTC, nanasess requested changes

2024-09-29 13:44 UTC, nanasess commented on data/class/SC_FormParam.php
> +        $objDate = new DateTime($db_date);
細かいところですが、 DateTimeImmutable にしておきましょうか。
```suggestion
        $objDate = new DateTimeImmutable($db_date);
```

2024-09-30 02:06 UTC, clicktx commented on data/class/SC_FormParam.php
> +        $objDate = new DateTime($db_date);
こちら修正してPRします

2024-10-04 06:06 UTC, nanasess approved these changes
LGTM

2024-10-06 23:57 UTC, merged