SC_Helper_Purchase:: getOrderTemp()の返り値を必ずarrayに
EC-CUBE/ec-cube2 pull request #1070
Opened 2024-11-28 05:46 UTC by clicktx

data/class/helper/SC_Helper_Purchase.php

```
2024/11/xx 13:04:38 [/shopping/confirm.php] Warning(E_WARNING): array_merge(): Expected parameter 1 to be an array, null given on [/path/data/class/pages/shopping/LC_Page_Shopping_Confirm.php(145)] from xxx.xxx.xxx.xxx
```

https://github.com/EC-CUBE/ec-cube2/blob/a22be23aa94e5b8c780b0328122f739ac35de968/data/class/pages/shopping/LC_Page_Shopping_Confirm.php#L118-L131

array_merge()で警告が出る時がある。
恐らく、注文完了後のブラウザバック等の時（未検証）

SC_Query::getRow()の返り値がnullなのが問題の原点ですが。

2024-12-08 13:42 UTC, nanasess requested changes
修正方針は問題ございません。

`SC_Helper_Purchase_getOrderTempTest::testGetOrderTemp存在しない受注IDを指定した場合結果が空になる()`  の結果が null を想定しているようですので、こちらも空の array に修正お願いできますでしょうか。

2024-12-08 13:42 UTC, nanasess commented on data/class/helper/SC_Helper_Purchase.php
> +        $result = $objQuery->getRow('*', 'dtb_order_temp', 'order_temp_id = ?', array($uniqId));
```suggestion
        $result = $objQuery->getRow('*', 'dtb_order_temp', 'order_temp_id = ?', [$uniqId]);
```
#996 より、short syntax に統一しているため修正をお願いします

2024-12-20 02:59 UTC, clicktx commented on data/class/helper/SC_Helper_Purchase.php
> +        $result = $objQuery->getRow('*', 'dtb_order_temp', 'order_temp_id = ?', array($uniqId));
@nanasess 
short syntaxの件、testの件承知しました。確かに最近short syntaxで書かれているな、と思っていました。

ところでですが、このような些細な修正（？）の時にもissueをたてたほうがいいか、悩ましいところです。。。

2024-12-20 07:20 UTC, nanasess commented on data/class/helper/SC_Helper_Purchase.php
> +        $result = $objQuery->getRow('*', 'dtb_order_temp', 'order_temp_id = ?', array($uniqId));
@clicktx ありがとうございます！ PR のみで済むものであれば、 issue なしでも問題ございません。

2024-12-20 07:21 UTC, nanasess approved these changes
LGTM

2024-12-20 08:05 UTC, merged

2024-12-23 09:09 UTC, clicktx commented on data/class/helper/SC_Helper_Purchase.php
> +        $result = $objQuery->getRow('*', 'dtb_order_temp', 'order_temp_id = ?', array($uniqId));
@nanasess ありがとうございます。issueなしでもokとの事、承知しました！