現在のカゴの中 [戻る]ボタン 購入手続きへ遷移することがある #803 (#806 を含む)
EC-CUBE/ec-cube2 pull request #814
Opened 2024-01-04 13:45 UTC by seasoftjapan

fixed #803
fixed #806

2024-01-04 16:51 UTC, nanasess commented
`str_starts_with` などの互換関数は、独自実装ではなく以下のような外部ライブラリに任せたいです。
https://packagist.org/packages/symfony/polyfill-php80
上記は PHP7.1+ なので、現状のシステム要件では入れられませんが #681 によってシステム要件が変更されれば活用できるようになります。あと半年くらいですので、それまで待つのはいかがでしょうか？

2024-01-05 09:21 UTC, seasoftjapan commented
@nanasess 
外部ライブラリに任せるのは賛成です。

ただ、差し迫った支障が無ければ、#681 が実現するまではこの PR を適用して、後続の Issue で置換すれば足りると考えますがいかがでしょうか?

2024-01-05 10:00 UTC, seasoftjapan commented
@nanasess 
もしかすると、差し迫った課題は、PHPStan を黙らせる対応が必要になる感じでしょうか。

2024-01-05 13:32 UTC, nanasess commented
@seasoftjapan 
PHPStan は以下で PR しているんですが、まだマージしていただけてない状況ですね
https://github.com/EC-CUBE/ec-cube2/pull/800

2024-01-05 13:34 UTC, nanasess commented
@seasoftjapan 
> ただ、差し迫った支障が無ければ、https://github.com/EC-CUBE/ec-cube2/issues/681 が実現するまではこの PR を適用して、後続の Issue で置換すれば足りると考えますがいかがでしょうか?

はい、 issues を登録しておいていただければ、それでも大丈夫です

2024-02-04 16:08 UTC, nanasess requested changes

2024-02-04 16:08 UTC, nanasess commented on data/class/SC_Initial.php
> +            function str_starts_with($haystack, $needle) {
PHPStan がエラーになっていますので、phpstan.neon.dist の ignoreErrors に入れておく等の対応をお願いいたします

2024-02-05 07:23 UTC, seasoftjapan commented on data/class/SC_Initial.php
> +            function str_starts_with($haystack, $needle) {
[e90cdb1](https://github.com/EC-CUBE/ec-cube2/pull/814/commits/e90cdb144bc4588097100246f70dd00a43428934) で対応しました。

2024-02-05 14:36 UTC, nanasess approved these changes

2024-02-14 07:48 UTC, merged