fix #296 商品一覧, 商品詳細のパフォーマンス改善の動作に関して #897
EC-CUBE/ec-cube2 pull request #898
Opened 2024-04-18 12:06 UTC by clicktx

#897 の修正コード
意図的にはこんな感じでしょうか？

2024-04-18 14:32 UTC, nanasess requested changes
#897 のご指摘をもとに、もう少しわかりやすくなるよう suggestion を入れてみました。ご確認お願いいたします🙇‍♂️

2024-04-18 14:32 UTC, nanasess commented on data/class/db/SC_DB_DBFactory.php
> +            $in = implode(",", $product_ids);
こちらはプレースホルダーのみを生成する意図ですので修正不要です🙇‍♂️

2024-04-18 14:32 UTC, nanasess commented on tests/class/SC_Product/SC_Product_listsTest.php
> +        $this->actual = $this->objProducts->lists($this->objQuery, array(1001, 1002));
通常、 SC_Product::lists() を使用する場合は、 SC_Query::setWhere() で `$where` 及び `$arrWhereVal` を設定します
```suggestion
        $this->objQuery->setWhere('product_id IN (?, ?)', array(1001, 1002));
        $this->actual = $this->objProducts->lists($this->objQuery);
```

2024-04-19 00:27 UTC, clicktx commented on tests/class/SC_Product/SC_Product_listsTest.php
> +        $this->actual = $this->objProducts->lists($this->objQuery, array(1001, 1002));
ありがとうございます。
既存2.13の改修中にハマった箇所なので明確な意図が書いてあると後々助かる方が増える気がします。
🙇

2024-04-20 07:36 UTC, clicktx commented
ご指摘通りの修正をコミットしました。
※プルリクしておいて何ですが、githubでの開発手順分かっていません..
これで良かったのか疑問ですが、なにかするべき事（または何もしなくても良い）があればコメント頂けると幸いです 🙇

2024-04-21 02:21 UTC, nanasess approved these changes
LGTM

2024-04-21 02:22 UTC, nanasess commented
ありがとうございます！良い感じですので Approve しました。
テストが通れば自動マージされます

2024-04-21 12:27 UTC, merged