登録メール送信時の警告を修正 #982
EC-CUBE/ec-cube2 pull request #989
Opened 2024-09-01 02:32 UTC by clicktx

fixed #982

2024-09-01 05:59 UTC, seasoftjapan requested changes
フロントに不具合が出る様子です。

SC_Helper_Mail::sfSendRegistMail() は、LC_Page_Admin_Customer からのみ使われており、LC_Page_Entry 及び lfSendRegistMail は、各ページクラス内に類似した処理を抱えている様子です。一方で、メールテンプレートは共用しているようです。

LC_Page_Entry 及び LC_Page_Regist も、SC_Helper_Mail::sfSendRegistMail() を呼び出して済ませばスマートな予感がします。

現況は LC_Page_Regist のみ Bcc を送信していないので、その部分で差異がでそうです。ただ、その仕様も不自然なので、何れも送信で統一されて良い気がします。

2024-09-05 08:59 UTC, clicktx commented
LC_Page_Admin_xxxクラスにメール送信処理が散らばっていて、テストしにくかったので後回しにしたのですが、影響ありましたね。。。

とりあえずテンプレートを戻すだけにしても良いかも知れませんが、回避案のようにSC_Helper_Mail::sfSendRegistMail() にまとめた方がスマートですね

2024-09-05 10:02 UTC, clicktx commented
どっちに書くべきか迷ったのですが、こちらに。


```
        if ($arrCustomerData['status'] == 1
             && (CUSTOMER_CONFIRM_MAIL == true || $resend_flg == true)
         ) {...
```

PR頂いて、条件式のリファクタリング部分を見ていて思ったのですが、
`$arrCustomerData['status'] == 1` = 「仮会員」の状態の時は「会員登録のご確認」メールを出すはずですよね？


条件を満たさないと「会員登録のご完了」メールが送信されるようになっている、と。
そうなると実は `&& (CUSTOMER_CONFIRM_MAIL == true || $resend_flg == true)` も不要なのではないかと思いました。


- `CUSTOMER_CONFIRM_MAIL == true`じゃないと仮会員にならないはず
- `$resend_flg` はそもそも不要なのでは説


https://github.com/EC-CUBE/ec-cube2/blob/fc5a36a25f2fff5179670351d65f890228b86e13/data/class/pages/entry/LC_Page_Entry.php#L194-L195

https://github.com/EC-CUBE/ec-cube2/blob/fc5a36a25f2fff5179670351d65f890228b86e13/data/class/pages/regist/LC_Page_Regist.php#L71-L72



`$arrCustomerData['status'] == 1`の状態の会員に「会員登録のご完了」メールを送る状況ってあるのでしょうか？？

2024-09-05 10:35 UTC, seasoftjapan commented
@clicktx 今回は、あくまでリファクタリングの範囲に留めて処理内容は変更していませんが、 私も漠然と違和感はありました。

もしかすると、CUSTOMER_CONFIRM_MAIL を途中変更した場合の考慮でしょうか。(実際に目的を達成しているか未検証です。)

第1引数・第2引数の被りも違和感ありますし、第3引数も今となっては不要なはずですし、色々と改善の余地はありそうに思います。本 Issue でどこまで扱うか難しいところですが。

2024-09-06 02:48 UTC, seasoftjapan approved these changes

2024-09-07 01:19 UTC, clicktx commented
> @seasoftjapan @clicktx 単に考慮できていなかっただけのように見えますね。 別の issues で対応しましょうか。



> @seasoftjapan @clicktx 単に考慮できていなかっただけのように見えますね。 別の issues で対応しましょうか。

issueたてました
https://github.com/EC-CUBE/ec-cube2/issues/1000#issue-2511357656

2024-09-09 00:17 UTC, nanasess commented
古いフォーマットのメールテンプレートの互換テストが欲しいので別途 issues 登録しますね

2024-09-09 00:18 UTC, nanasess approved these changes
LGTM

2024-09-09 00:53 UTC, merged