PHP-CS-Fixer の導入
EC-CUBE/ec-cube2 pull request #996
Opened 2024-09-05 08:58 UTC by nanasess

- `strlen($val)` で null チェックしているのを修正するのが主目的
- その他、統一した方が良さそうなルールを適用

2024-09-05 09:49 UTC, seasoftjapan commented
[6f20c7d](https://github.com/EC-CUBE/ec-cube2/pull/996/commits/6f20c7dadd830f101c6ab994f39cc3ffa79bd29a) は、全て PHP-CS-Fixer による変更ですか?

ローカルで [bfc9f5d](https://github.com/EC-CUBE/ec-cube2/pull/996/commits/bfc9f5d996c7318e88aefa5d85a55eee11404c2f) から実行を試したのですが、結果が異なる様子でして。
```
$ data/vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run
Loaded config default from "****/.php-cs-fixer.dist.php".
   1) data/class/SC_Customer.php
   2) data/class/helper/SC_Helper_TaxRule.php
   3) data/class/helper/SC_Helper_CSV.php
   4) data/class/SC_Fpdf.php
   5) data/class/pages/guide/LC_Page_Guide_Kiyaku.php
   6) data/class/pages/shopping/LC_Page_Shopping.php
   7) data/class/pages/products/LC_Page_Products_List.php
   8) data/class/pages/admin/contents/LC_Page_Admin_Contents_Recommend.php
   9) data/class/pages/admin/contents/LC_Page_Admin_Contents_RecommendSearch.php
  10) data/class/pages/admin/mail/LC_Page_Admin_Mail_Preview.php
  11) data/class/pages/admin/design/LC_Page_Admin_Design.php
  12) data/class/pages/admin/design/LC_Page_Admin_Design_MainEdit.php
  13) data/class/pages/admin/order/LC_Page_Admin_Order_Mail.php
  14) data/class/pages/admin/order/LC_Page_Admin_Order_Edit.php
  15) data/class/pages/admin/order/LC_Page_Admin_Order_Disp.php
  16) data/class/pages/admin/order/LC_Page_Admin_Order_ProductSelect.php
  17) data/class/pages/admin/products/LC_Page_Admin_Products_Product.php
  18) data/class/pages/mypage/LC_Page_Mypage_Favorite.php
  19) data/module/HTTP/Request.php

Checked all files in 20.817 seconds, 24.000 MB memory used
```

正しい実行手順を教えていただけますと幸いです。

2024-09-05 12:34 UTC, nanasess commented
@seasoftjapan 
そのままだと composer.json の `config.platform.php: 7.4.0` が有効になっていて、PHP8.0以降のルールが適用されないようです。
以下でいかがでしょうか？

```
PHP_CS_FIXER_IGNORE_ENV=1 data/vendor/bin/php-cs-fixer fix --allow-risky=yes
```

2024-09-05 12:34 UTC, nanasess commented
テストが落ちているようなので、一旦 Draft に戻します

2024-09-06 00:59 UTC, nanasess commented
未定義変数、連想配列の扱いに難がありそう

2024-09-06 11:44 UTC, seasoftjapan commented on data/class/SC_CartSession.php
> -                                        複数に配送する場合は都道府県IDの配列
消失しているようです。

2024-09-06 11:44 UTC, seasoftjapan commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
カンマの後、改行してくれるオプションとか無いでしょうか?
いくつか、気持ちの悪い(中途半端な)印象の整形がありました。

2024-09-06 11:44 UTC, seasoftjapan commented on data/class/api/operations/ItemSearch.php
> +                // 販売価格が高い順
これ、救えないですかね。case のコメントで、case の真上に欲しいです。

2024-09-06 11:44 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'array_syntax' => false,
デフォルト short だと思いますが、不都合ありそうでしたか?
個人的には、少なくとも混在するのは嫌で、統一するなら short 一択かなといった印象です。

2024-09-06 11:44 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'single_quote' => false,
デフォルトでなかなか良い感じの置換をする様子ですが、目に付くパターンありましたか?

2024-09-06 11:44 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'native_constant_invocation' => false,
これが適用されていなそうな置換が見受けられます。

例
``` diff
-                trigger_error('最大階層制限到達', E_USER_ERROR);
+                trigger_error('最大階層制限到達', \E_USER_ERROR);
```

当方環境 (PHP 8.3.9 / FROM ghcr.io/ec-cube/ec-cube2-php/8.3-apache) では、置換されないようです。

2024-09-06 11:44 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +$rules = [
設定理由をソースコメントに残していただけると、参考になります。
特に無効化している項目ですが、具体的に不都合があったのか、何となく避けたかといった辺り分かると、今回は対応を見送っても、今後の対応拡大に繋げやすいと思います。
下に、何項目かコメントつけましたが、無理に今回対応しなくても、後々で良いのかなと思う部分もあります。

2024-09-06 11:44 UTC, seasoftjapan commented on data/class/SC_Batch.php
> - * @package Page
@package は不要との判断でしょうか?

以前に、phpDocumentor で出力したときに「あー 分類されるんだ」と思ったくらいで、さほど必要になることは無いと思いますが。

rules 的には対象でない気がして、気になりました。

2024-09-09 00:11 UTC, nanasess commented
@seasoftjapan ありがとうございます！おおむね対応可能だと思いますので、順次対応していきますね

2024-09-20 12:59 UTC, nanasess commented on .php-cs-fixer.dist.php
> +    'array_syntax' => false,
変更が多くなりすぎるため、2.13からバージョンアップする際のコンフリクト解消が辛くなるんじゃないかと思って変換しないようにしてました。

1. 2.13 の状態で、一旦 php-cs-fixer のルールを適用
2. 2.17 のブランチをマージ
とすれば、少しはコンフリクトもマシになりそうですかね

2024-09-20 13:01 UTC, nanasess commented on .php-cs-fixer.dist.php
> +    'single_quote' => false,
`'single_quote'` ですかね。こちらも `array_syntax` と同じ理由で false にしていました。

2.13 に php-cs-fixer を適用する手順で問題なさそうであれば、 true にしたいと思います

2024-09-20 13:02 UTC, nanasess commented on .php-cs-fixer.dist.php
> +    'native_constant_invocation' => false,
手元の環境の問題っぽいです。確認してみます

2024-09-21 07:39 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'array_syntax' => false,
array_syntax のみの影響度合いは把握できていませんが、他の項目でスペースを変更されるのもマージ時には辛いかもとは思いました。私も対処方法として、2.13 側にも PHP-CS-Fixer を同じ設定で適用するのが良さそうに思いました。

2024-09-21 07:43 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'single_quote' => false,
> `'single_quote'` ですかね。

はい。1行を指定してコメントつけたつもりですが、上3行も自動引用されたようで、分かりにくくなり恐縮です。

2024-09-29 15:14 UTC, nanasess commented
2.13.x のソースに対しても同様のルールを適用できそうなので、これを活用すれば旧バージョンからのマージや PHP8 対応も楽にできそう

2024-09-30 15:30 UTC, nanasess commented on .php-cs-fixer.dist.php
> +    'native_constant_invocation' => false,
native_constant_invocation が適用されていたようですので対応します

2024-09-30 15:34 UTC, nanasess commented on data/class/SC_Batch.php
> - * @package Page
`@Symfony` で phpdoc_no_package が適用されているようです。
https://cs.symfony.com/doc/rules/phpdoc/phpdoc_no_package.html
`phpdoc_no_package => true` で良いと思います

2024-09-30 16:02 UTC, nanasess commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
`trailing_comma_in_multiline => false` にしたいと思います
https://cs.symfony.com/doc/rules/control_structure/trailing_comma_in_multiline.html

2024-09-30 16:46 UTC, nanasess commented on data/class/api/operations/ItemSearch.php
> +                // 販売価格が高い順
`'statement_indentation' => ['stick_comment_to_next_continuous_control_statement' => true]` とすることで対応できそうです。
https://cs.symfony.com/doc/rules/whitespace/statement_indentation.html
が、 composer の依存関係の問題で、現在 php-cs-fixer 3.9.5 がインストールされています。
このバージョンでは上記オプションは未実装のため、利用できないようです。
PHPUnit のバージョンを上げることで、上記オプションも利用できるようになりそうなので、別途対応しようと思います。

2024-09-30 17:11 UTC, nanasess commented
@seasoftjapan
以下のルールを見直してみました
- `single_quote => true` に変更(4系にあわせる)
- `concat_space => ['spacing' => 'none']` に変更(4系にあわせる)
- `array_syntax => true` に変更(4系にあわせる)
- `phpdoc_scalar => true` に変更(phpdoc の int や bool を統一したい)
- `data/smarty_extends` 及び `tests` にも適用

各ルールにコメントも入れておきましたのでご確認お願いいたします🙇‍♂️
https://github.com/EC-CUBE/ec-cube2/pull/996/commits/94d493cd94b96a0b337b11a6c09da17869c282ae

2024-10-02 04:04 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'trailing_comma_in_multiline' => false, // `, ]` となるケースを防ぐため
今後の Diff を整えられるメリットを考えるとケツカンマは徹底したいです。

配列末尾のコーディングスタイルが、PHP-CS-Fixer が想定していイレギュラーな形式なのが原因のようですね。このコーディングも修正するルールがあればベストですが、ざっと確認した範囲では見つけられませんでした。

`, ]` となる箇所は私が修正しようと思いますが、どの流れが良いですか?
- https://github.com/nanasess/ec-cube2/tree/php-cs-fixer ベースで修正して PR する。
- `, ]` となる箇所を master ベースで修正して、https://github.com/nanasess/ec-cube2/tree/php-cs-fixer へ PR する。
- `, ]` となる箇所を master ベースで修正して、master  へ PR する。
- 別 Issue で後続の対応とする。そのタイミングでルール削除する。
- 本 PR はルールを戻して、`, ]` となった箇所を別 Issue で修正する。

2024-10-02 04:16 UTC, seasoftjapan commented on .php-cs-fixer.dist.php
> +    'trailing_comma_in_multiline' => false, // `, ]` となるケースを防ぐため
https://github.com/EC-CUBE/ec-cube2/pull/996#discussion_r1746885367 で言及している部分でした。そちらへ転記して、こちらは削除します。

2024-10-02 04:24 UTC, seasoftjapan commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
気持ち悪いですが、それでも今後の Diff を整えられる全体的なメリットを考えると、ケツカンマの徹底は優先して良いと思います。

とは言え、やはり気持ち悪いし、その箇所は Diff を改善できないので、`, ]` となる箇所は私が修正しようと思います。どの流れが良いとかありますか?
- https://github.com/nanasess/ec-cube2/tree/php-cs-fixer ベースで修正して PR する。
- `, ]` となる箇所を master ベースで修正して、https://github.com/nanasess/ec-cube2/tree/php-cs-fixer へ PR する。
- `, ]` となる箇所を master ベースで修正して、master  へ PR する。
- 別 Issue で後続の対応とする。そのタイミングでルール削除する。
- 本 PR はルールを戻して、`, ]` となった箇所を別 Issue で修正する。

2024-10-02 13:20 UTC, nanasess commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
@seasoftjapan 
> 本 PR はルールを戻して、, ] となった箇所を別 Issue で修正する。

この対応にしましょうかね。
`trailing_comma_in_multiline => false`  は削除しておきます(`@Symfony` に含まれているため)

2024-10-02 13:37 UTC, nanasess commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
`trailing_comma_in_multiline => false` は削除して再度 fix しておきました
https://github.com/EC-CUBE/ec-cube2/pull/996/commits/20138d0f245fccda79649992170cd6dcdf552fa9

2024-10-02 14:05 UTC, seasoftjapan commented on data/class/api/operations/CartAdd.php
> +            'Version' => ECCUBE_VERSION, );
ありがとうございます。
#1017 登録しました。

2024-10-03 00:53 UTC, seasoftjapan approved these changes

2024-10-03 02:45 UTC, nanasess commented
GitHub Actions のエラーは以下 PR で解消予定
https://github.com/EC-CUBE/ec-cube2/pull/1018

2024-10-03 02:49 UTC, nanasess commented on data/class/api/operations/ItemSearch.php
> +                // 販売価格が高い順
以下 PR 作成しました
https://github.com/EC-CUBE/ec-cube2/issues/1020

2024-10-03 08:27 UTC, seasoftjapan requested changes
1点忘れてました。

> * `concat_space => ['spacing' => 'none']` に変更(4系にあわせる)

2系で準拠してきた、Zend Framework PHP 標準コーディング規約と相違するため気になりました。

Laravel 界隈以外では、一般的でない気がするのですが、どうでしょうか?

正直 ` . ` と打つの面倒くせーと思うこともありますけどね。

これまで主に読みやすさの観点で推奨されていたと思うので、それこそコーディング中は `.` で実装して、PHP-CS-Fixer で ` . ` に整形してもらうとかも有りかなと思いました。

2024-10-03 13:43 UTC, nanasess commented
@seasoftjapan 
2系と4系で、スペース有無を使い分けるのはナンセンスだなと思い、4系に合わせました。
従来のコーディング規約と異なるのは承知の上なんですが、多くのルールを Symfony に準拠しているので、こちらも合わせた方が混乱が少ないかなと思ってます

2024-10-03 14:44 UTC, seasoftjapan commented
ルールに concat_space を追加したと思いましたが、逆に削除したのですね。で、@Symfony に concat_space が設定されていて、デフォルトは `['spacing' => 'one']` であると。

可逆なルールだと思いますし、とりあえずそのスタイルで試してみるのも良さそうですね。

2024-10-03 14:45 UTC, seasoftjapan approved these changes

2024-10-06 16:46 UTC, merged

2025-01-09 11:06 UTC, seasoftjapan commented on data/class/api/operations/ItemSearch.php
> +                // 販売価格が高い順
https://github.com/EC-CUBE/ec-cube2/issues/1020 適用後も崩れるようです。

switch 使える宗派への迫害ですね😁 > PHP-CS-Fixer/PHP-CS-Fixer

case 直前に `// no break` みたいな使われ方もあるので、ケアしきれないのですかね。case は手出ししないとかできると良いですが、用意されていないですかね。